name: grab
description: A set of mixins and extension methods as an alternative to ListenableBuilder / ValueListenableBuilder, good for state management.
version: 0.4.1
repository: https://github.com/kaboc/grab

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
