name: grab
description: A flutter package to control rebuilds of a widget based on updates of a Listenable such as ChangeNotifier and ValueNotifier.
version: 0.2.2
homepage: https://github.com/kaboc/grab

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
