name: grab
description: A flutter package to control rebuilds of a widget based on updates of a Listenable.
version: 0.1.0
homepage: https://github.com/kaboc/grab

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
